### ISSUE TITLE
TypeError: this.subsReady is not a function

### ISSUE THREAD

**Issue by madshargreave** [grovelabs/meteor-react#8]
Feed = React.createClass({
  mixins: [ReactiveMixin, DDPMixin],

I am following the same structure as in the example provided in the docs, but I get the following error when checking if my component's subscriptions are ready.

```
Exception from Tracker recompute function:
debug.js:41 TypeError: this.subsReady is not a function
    at getReactiveState (feed.jsx:21) 
```

Code:

```
Feed = React.createClass({
  mixins: [ReactiveMixin, DDPMixin],

  subscriptions: function() {
    var user            = Meteor.user();
    var preferences     = !user || user.preferences;
    var activeChannelId = !preferences || preferences.activeChannelId;

    return Meteor.subscribe('commentThreads', activeChannelId)
  },

  getInitialState: function() {
    return {
      selectedItem: null,
      commentThreads: []
    };
  },

  getReactiveState: function() {
    console.log(this);
    if (this.subsReady()) {
      return {
        commentThreads: CommentThreads.find().fetch()
      };
    }
  }
...
```

**Comment by lourd** [comment]
Hello!

Your issue is the order of the mixins. Lifecycle methods for the mixins run in the order they're listed in the component. In this case, that means `getInitialState` for ReactiveMixin runs before `getInitialState` for DDPMixin. DDPMixin hasn't had the chance to [initialize](https://github.com/grovelabs/meteor-react/blob/master/src/DDPMixin.js#L36) the `subsReady` function yet so it's undefined.

So the fix is to put DDPMixin before ReactiveMixin. I'll update the docs to make that more clear
